# This file was generated by GoReleaser. DO NOT EDIT.
cask "iddio" do
  name "iddio"
  desc "Security gateway for AI agent access to Kubernetes clusters"
  homepage "https://iddio.dev"
  version "2026.0220.2306"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iddio"

  on_macos do
    on_intel do
      url "https://github.com/leonardaustin/iddio/releases/download/v#{version}/iddio_#{version}_darwin_amd64.tar.gz"
      sha256 "70f960fce66f5f0be0bd3b6eeb42dad6d63763be051d94b60568215419fb5b96"
    end
    on_arm do
      url "https://github.com/leonardaustin/iddio/releases/download/v#{version}/iddio_#{version}_darwin_arm64.tar.gz"
      sha256 "748feede485ebc775712f46f6993427b61e4f17ce8e916ecb37c895e8785dd26"
    end
  end

  # No zap stanza required
end
