# This file was generated by GoReleaser. DO NOT EDIT.
cask "msh" do
  version "0.2.25"

  on_macos do
    on_intel do
      sha256 "c6de11ce1ea942af2c14ae43c56688090bff99f1072c289f7b5feabfec07c34d"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "90eefb78a5d722983e219a6d66393781a06e33a2291a3b97f5dcb32d150850bd"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "437a16380585915f1c81425f1bc5d6fc11806fb0d83fb373d64971e81073be11"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "39feaed31bf3926598410aff27953a9275ca0515201668732fc4321bbf0752ab"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-linux-arm64.tar.gz"
    end
  end

  name "msh"
  desc "Mezite client — secure infrastructure access"
  homepage "https://mezite.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "msh"

  # No zap stanza required

end
