# This file was generated by GoReleaser. DO NOT EDIT.
cask "msh" do
  version "0.2.24"

  on_macos do
    on_intel do
      sha256 "296b543cc9fe950008e3400ad27df4a56aa9de942de139e53335d32fcaae8368"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "96c6079587204962b456c0910ffaf0d542676bc3604a094ce45a290161a2897d"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e7a157574aa25a98a8d4c8b30c8396c244afec9da50d21ef7bd6f59bf3d093bf"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "6293d002dfd8dc9b38895719244395033d6cfe8a75d94b660da0d0c7718f1f2a"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-linux-arm64.tar.gz"
    end
  end

  name "msh"
  desc "Mezite client — secure infrastructure access"
  homepage "https://mezite.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "msh"

  # No zap stanza required

end
