# This file was generated by GoReleaser. DO NOT EDIT.
cask "msh" do
  version "0.2.26"

  on_macos do
    on_intel do
      sha256 "75b51ad1d9fd7ef146f7022c7a711555bb7ba54cd9d20f12849d3c08e81f48e0"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "3fa969b14b266244e7cc25cd4222aa59f0a3a8ad6cce6163bd71c155a12a20ca"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4d664dd4c225420ab5cef0d6bf26e2efacf0ddd53ff710afb1cf1733ac0dd543"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "57f819fde7e267b8d955b4e41d323b35c0f08ec37042f8aa814db3b79eb4e64b"
      url "https://github.com/leonardaustin/mezite/releases/download/v#{version}/mezite-linux-arm64.tar.gz"
    end
  end

  name "msh"
  desc "Mezite client — secure infrastructure access"
  homepage "https://mezite.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "msh"

  # No zap stanza required

end
